version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    cooldown:
      default-days: 3
    labels:
      - "dependencies"
      - "github-actions"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
    groups:
      actions:
        patterns:
          - "*"
